# Indienstein 工具箱 - GitHub Pages 配置

# 站点信息
title: Indienstein 工具箱
description: JtheWL 的个人实用工具集合
url: "https://jupiterthewarlock.github.io/Indienstein-by-JtheWL/"
baseurl: "/Indienstein-by-JtheWL"

# 作者信息
author:
  name: JtheWL
  email: your-email@example.com

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages 设置
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - README.md 